"""Add document_chunk

Revision ID: 76a2098e2ef0
Revises: 
Create Date: 2026-09-28 12:37:50.940715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76a2098e2ef0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'DRAFT', 'SUPERSEDED', 'EXPIRED', name='documentstatus'), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('asset_class', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('parent_chunk_id', sa.UUID(), nullable=True),
    sa.Column('chunk_type', sa.Enum('HEADER', 'SECTION', 'LEAF_PARAGRAPH', 'TABLE_SUMMARY', 'RAW_TABLE', 'MARKDOWN_SECTION', name='chunktype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bounding_box_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tree_path', sa.String(length=500), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['document_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('response_text', sa.String(), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('faithfulness_score', sa.Float(), nullable=True),
    sa.Column('as_of_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disclosures_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_logs')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('documents')
    # ### end Alembic commands ###
